### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by ghost** [sunqueen/vlc-2.2.1.32-2013#2]
Hi: 
I just downloaded your code and tried to build with VS2013. But I get this below error message
"VLC media player could not start. Either the command line options were invalid or no plugins were found"

I can see "--media-library" command goes into function but somehow it returns null and fails to build.
So I wonder if I need to install additional package to build your files. 

Thanks in advance

**Comment by sunqueen** [comment]
Hi.

Do you patch VS2013? 
Original version has many problems.
Please patch that.
2.0 or next version.

Have a nice day!!!
